/**
 * Screenshot capture orchestration.
 * Handles worktree setup, dev server, auth, and headless/interactive/story-aware capture.
 */

import { execFileSync } from "child_process";
import { existsSync, mkdirSync, rmSync } from "fs";
import { createInterface } from "readline";
import { join, resolve } from "path";
import type { ScreenshotConfig, ScreenshotMapping } from "../types.js";
import type { ProgressReporter } from "../progress.js";
import { installDeps, startDevServer, waitForServer, killServer } from "./dev-server.js";
import { checkExistingAuth, performBrowserAuth, handleStaleAuth } from "./auth.js";
import type { ChildProcess } from "child_process";
import type { StoryInput, ScreenshotScenario } from "./scenarios.js";
export type { ScreenshotScenario } from "./scenarios.js";

const SCREENSHOT_DIR = "/tmp/vibe-screenshots";

// ---------------------------------------------------------------------------
// Story-aware capture: produces named screenshots mapped to specific stories
// ---------------------------------------------------------------------------

export interface StoryAwareCaptureConfig extends ScreenshotConfig {
  stories: StoryInput[];
  /** Pre-built scenarios JSON (generated by Claude in conversation). */
  prebuiltScenarios?: ScreenshotScenario[];
}

/**
 * Capture story-specific screenshots by interacting with the page.
 *
 * Scenarios must be provided as prebuiltScenarios (generated by Claude
 * in conversation and saved as JSON). Use --scenarios <file> in the CLI.
 *
 * Returns ScreenshotMapping[] with each story's screenshots already matched.
 */
export async function captureStoryScreenshots(
  config: StoryAwareCaptureConfig,
  routes: string[],
  authStatePath: string,
  progress: ProgressReporter,
): Promise<ScreenshotMapping[]> {
  if (existsSync(SCREENSHOT_DIR)) rmSync(SCREENSHOT_DIR, { recursive: true });
  mkdirSync(SCREENSHOT_DIR, { recursive: true });

  const staticRoutes = routes.filter(
    (r) => !r.includes("[") && !r.includes(":")
  );
  if (staticRoutes.length === 0) {
    progress.report("  No static routes to screenshot (all routes have dynamic params)");
    return [];
  }

  // Scenarios must be pre-built (generated by Claude in conversation)
  let scenarios: ScreenshotScenario[];

  if (config.prebuiltScenarios && config.prebuiltScenarios.length > 0) {
    scenarios = config.prebuiltScenarios;
    progress.report(`  Using ${scenarios.length} pre-built screenshot scenarios`);
  } else {
    progress.report("  No pre-built scenarios provided — cannot capture story screenshots");
    progress.report("  Tip: use --scenarios <file> to provide scenarios JSON");
    return [];
  }

  if (scenarios.length === 0) {
    progress.report("  No screenshot scenarios generated");
    return [];
  }

  let workDir: string = "";
  let createdWorktree = false;
  let serverProcess: ChildProcess | null = null;

  try {
    // Worktree/branch setup (same as before)
    let currentBranch = "";
    try {
      currentBranch = execFileSync(
        "git",
        ["-C", config.vibeRepo, "rev-parse", "--abbrev-ref", "HEAD"],
        { encoding: "utf-8" }
      ).trim();
    } catch {
      /* ignore */
    }

    if (currentBranch === config.vibeBranch) {
      progress.report(`  Branch "${config.vibeBranch}" is already checked out — using repo directly`);
      workDir = config.vibeRepo;
    } else {
      const worktreeDir = `/tmp/vibe-worktree-${Date.now()}`;
      progress.report("  Creating worktree for vibe branch...");
      execFileSync(
        "git",
        ["-C", config.vibeRepo, "worktree", "add", worktreeDir, config.vibeBranch],
        { encoding: "utf-8" }
      );
      workDir = worktreeDir;
      createdWorktree = true;
    }

    // Resolve app directory — standalone repos have the app at root,
    // monorepos have it under a subdirectory like apps/customer-portal
    const candidatePath = config.appDir === "." ? workDir : join(workDir, config.appDir);
    const appFullPath = existsSync(candidatePath) ? candidatePath : workDir;

    progress.report("  Installing dependencies...");
    installDeps(workDir, appFullPath);

    progress.report(`  Starting dev server on port ${config.port}...`);
    serverProcess = startDevServer(appFullPath, config.port);

    const serverReady = await waitForServer(
      `http://localhost:${config.port}`,
      90_000,
    );
    if (!serverReady) {
      progress.report("  Dev server failed to start within 90s — skipping screenshots");
      return [];
    }
    progress.report("  Dev server ready");

    const { chromium } = await import("playwright");

    // Auth flow
    progress.report("  Checking authentication...");
    const persistentAuthPath = resolve(authStatePath);
    let storageStatePath: string | null = null;

    const authCheck = checkExistingAuth(persistentAuthPath, progress);
    storageStatePath = authCheck.storageStatePath;

    if (!storageStatePath) {
      storageStatePath = await performBrowserAuth(
        chromium,
        config.port,
        persistentAuthPath,
        progress,
      );
      if (!storageStatePath) return [];
    }

    // Execute scenarios
    return await executeScenarios(
      chromium, scenarios, config.stories, config.port, storageStatePath,
      persistentAuthPath, progress,
    );
  } catch (err) {
    progress.error(`Screenshot error: ${(err as Error).message.split("\n")[0]}`);
    return [];
  } finally {
    if (serverProcess) killServer(serverProcess);
    if (createdWorktree) {
      try {
        execFileSync(
          "git",
          ["-C", config.vibeRepo, "worktree", "remove", workDir, "--force"],
          { stdio: "ignore" },
        );
      } catch {
        /* best effort */
      }
    }
  }
}

async function executeScenarios(
  chromium: typeof import("playwright").chromium,
  scenarios: ScreenshotScenario[],
  stories: StoryInput[],
  port: number,
  storageStatePath: string,
  persistentAuthPath: string,
  progress: ProgressReporter,
): Promise<ScreenshotMapping[]> {
  const { executeScenario } = await import("./scenarios.js");

  progress.report("  Executing screenshot scenarios...");
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({
    viewport: { width: 1440, height: 900 },
    storageState: storageStatePath,
  });
  const page = await context.newPage();

  // Group results by story key
  const storyScreenshots = new Map<string, string[]>();

  for (const scenario of scenarios) {
    progress.report(`    [${scenario.storyKey}] ${scenario.label}...`);

    const filepath = await executeScenario(
      page, scenario, port, SCREENSHOT_DIR, progress,
    );

    if (filepath) {
      const existing = storyScreenshots.get(scenario.storyKey) ?? [];
      existing.push(filepath);
      storyScreenshots.set(scenario.storyKey, existing);
      progress.report(`    [OK] ${scenario.storyKey} -> ${scenario.label}.png`);
    }

    // Check for stale auth on first screenshot
    if (page.url().includes("/login") || page.url().includes("/auth")) {
      if (storyScreenshots.size === 0) {
        handleStaleAuth(persistentAuthPath, progress);
        break;
      }
    }
  }

  await browser.close();

  // Build ScreenshotMapping[] from results
  const mappings: ScreenshotMapping[] = [];
  let totalCaptures = 0;
  for (const [storyKey, paths] of storyScreenshots) {
    totalCaptures += paths.length;
    const story = stories.find((s) => s.key === storyKey);
    mappings.push({
      storyKey,
      storySummary: story?.summary ?? storyKey,
      screenshotPaths: paths,
    });
  }

  progress.report(`  Captured ${totalCaptures} screenshots for ${storyScreenshots.size} stories`);
  return mappings;
}

// ---------------------------------------------------------------------------
// Original route-based capture (unchanged)
// ---------------------------------------------------------------------------

export async function captureScreenshots(
  config: ScreenshotConfig,
  routes: string[],
  authStatePath: string,
  progress: ProgressReporter
): Promise<Map<string, string>> {
  const screenshots = new Map<string, string>();

  if (existsSync(SCREENSHOT_DIR)) rmSync(SCREENSHOT_DIR, { recursive: true });
  mkdirSync(SCREENSHOT_DIR, { recursive: true });

  const staticRoutes = routes.filter(
    (r) => !r.includes("[") && !r.includes(":")
  );
  if (staticRoutes.length === 0) {
    progress.report(
      "  No static routes to screenshot (all routes have dynamic params)"
    );
    return screenshots;
  }

  let workDir: string = "";
  let createdWorktree = false;
  let serverProcess: ChildProcess | null = null;

  try {
    // Check if branch is already checked out
    let currentBranch = "";
    try {
      currentBranch = execFileSync(
        "git",
        ["-C", config.vibeRepo, "rev-parse", "--abbrev-ref", "HEAD"],
        { encoding: "utf-8" }
      ).trim();
    } catch {
      /* ignore */
    }

    if (currentBranch === config.vibeBranch) {
      progress.report(
        `  Branch "${config.vibeBranch}" is already checked out — using repo directly`
      );
      workDir = config.vibeRepo;
    } else {
      const worktreeDir = `/tmp/vibe-worktree-${Date.now()}`;
      progress.report("  Creating worktree for vibe branch...");
      execFileSync(
        "git",
        [
          "-C",
          config.vibeRepo,
          "worktree",
          "add",
          worktreeDir,
          config.vibeBranch,
        ],
        { encoding: "utf-8" }
      );
      workDir = worktreeDir;
      createdWorktree = true;
    }

    const appFullPath =
      config.appDir === "." ? workDir : join(workDir, config.appDir);

    progress.report("  Installing dependencies...");
    installDeps(workDir, appFullPath);

    progress.report(`  Starting dev server on port ${config.port}...`);
    serverProcess = startDevServer(appFullPath, config.port);

    const serverReady = await waitForServer(
      `http://localhost:${config.port}`,
      90_000
    );
    if (!serverReady) {
      progress.report(
        "  Dev server failed to start within 90s — skipping screenshots"
      );
      return screenshots;
    }
    progress.report("  Dev server ready");

    const { chromium } = await import("playwright");

    // Auth flow
    progress.report("  Checking authentication...");
    const persistentAuthPath = resolve(authStatePath);
    let storageStatePath: string | null = null;

    const authCheck = checkExistingAuth(persistentAuthPath, progress);
    storageStatePath = authCheck.storageStatePath;

    if (!storageStatePath) {
      storageStatePath = await performBrowserAuth(
        chromium,
        config.port,
        persistentAuthPath,
        progress
      );
      if (!storageStatePath) return screenshots;
    }

    if (config.interactiveScreenshots) {
      await captureInteractive(
        chromium, staticRoutes, config.port, storageStatePath, screenshots, progress
      );
    } else {
      await captureHeadless(
        chromium, staticRoutes, config.port, storageStatePath,
        persistentAuthPath, screenshots, progress
      );
    }
  } catch (err) {
    progress.error(
      `Screenshot error: ${(err as Error).message.split("\n")[0]}`
    );
  } finally {
    if (serverProcess) killServer(serverProcess);
    if (createdWorktree) {
      try {
        execFileSync(
          "git",
          [
            "-C",
            config.vibeRepo,
            "worktree",
            "remove",
            workDir!,
            "--force",
          ],
          { stdio: "ignore" }
        );
      } catch {
        /* best effort */
      }
    }
  }

  return screenshots;
}

async function captureHeadless(
  chromium: typeof import("playwright").chromium,
  routes: string[],
  port: number,
  storageStatePath: string,
  persistentAuthPath: string,
  screenshots: Map<string, string>,
  progress: ProgressReporter
): Promise<void> {
  progress.report("  Capturing screenshots...");
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({
    viewport: { width: 1440, height: 900 },
    storageState: storageStatePath,
  });
  const page = await context.newPage();

  for (const route of routes) {
    const url = `http://localhost:${port}${route}`;
    try {
      const response = await page.goto(url, {
        waitUntil: "networkidle",
        timeout: 15_000,
      });

      if (page.url().includes("/login") || page.url().includes("/auth")) {
        if (screenshots.size === 0) {
          handleStaleAuth(persistentAuthPath, progress);
          break;
        }
        progress.report(`    [SKIP] ${route} — requires authentication`);
        continue;
      }

      if (response && response.status() >= 400) {
        progress.report(`    [SKIP] ${route} — HTTP ${response.status()}`);
        continue;
      }

      await page.waitForTimeout(2_000);

      const filename =
        (route === "/"
          ? "index"
          : route.replace(/\//g, "_").replace(/^_/, "")) + ".png";
      const filepath = join(SCREENSHOT_DIR, filename);
      await page.screenshot({ path: filepath, fullPage: true });
      screenshots.set(route, filepath);
      progress.report(`    [OK] ${route} -> ${filename}`);
    } catch (err) {
      progress.report(
        `    [FAIL] ${route} — ${(err as Error).message.split("\n")[0]}`
      );
    }
  }

  await browser.close();
}

async function captureInteractive(
  chromium: typeof import("playwright").chromium,
  routes: string[],
  port: number,
  storageStatePath: string,
  screenshots: Map<string, string>,
  progress: ProgressReporter
): Promise<void> {
  progress.report(
    "  Interactive screenshot mode — a browser window will open."
  );
  progress.report(
    "  For each route: interact with the UI, then press Enter to capture."
  );
  progress.report(
    "  You can capture multiple states per route. Type 'skip' to skip, 'done' to finish.\n"
  );

  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const ask = (q: string) =>
    new Promise<string>((res) => rl.question(q, (a) => res(a.trim())));

  const browser = await chromium.launch({ headless: false });
  const context = await browser.newContext({
    viewport: { width: 1440, height: 900 },
    storageState: storageStatePath,
  });
  const page = await context.newPage();

  for (const route of routes) {
    const url = `http://localhost:${port}${route}`;
    try {
      await page.goto(url, { waitUntil: "networkidle", timeout: 15_000 });

      if (page.url().includes("/login") || page.url().includes("/auth")) {
        progress.report(`    [SKIP] ${route} — requires authentication`);
        continue;
      }

      progress.report(`\n  Route: ${route}`);
      let captureNum = 1;

      while (true) {
        const defaultName =
          (route === "/"
            ? "index"
            : route.replace(/\//g, "_").replace(/^_/, "")) +
          (captureNum > 1 ? `_${captureNum}` : "");
        const input = await ask(
          `    Press Enter to capture as "${defaultName}" (or type name/skip/done): `
        );

        if (input.toLowerCase() === "skip") break;
        if (input.toLowerCase() === "done") {
          rl.close();
          await browser.close();
          return;
        }

        const filename = (input || defaultName) + ".png";
        const filepath = join(SCREENSHOT_DIR, filename);
        await page.screenshot({ path: filepath, fullPage: true });
        const routeLabel =
          captureNum > 1 ? `${route}#${captureNum}` : route;
        screenshots.set(routeLabel, filepath);
        progress.report(`    [OK] captured -> ${filename}`);
        captureNum++;
      }
    } catch (err) {
      progress.report(
        `    [FAIL] ${route} — ${(err as Error).message.split("\n")[0]}`
      );
    }
  }

  rl.close();
  await browser.close();
}
