/**
 * Story-aware screenshot scenarios.
 *
 * Scenarios are pre-built JSON (generated by Claude in conversation) that
 * define Playwright interaction scripts to capture meaningful UI states
 * for each story. Each story gets 1-3 distinct screenshots.
 */

import type { Page } from "playwright";
import type { ProgressReporter } from "../progress.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** A single action Playwright should perform before taking a screenshot. */
export interface ScenarioAction {
  /** What to do: navigate, type, click, wait, clear, press, scroll */
  action: "navigate" | "type" | "click" | "wait" | "clear" | "press" | "scroll";
  /** CSS selector, placeholder text, or URL depending on action */
  target?: string;
  /** Value to type, key to press, or ms to wait */
  value?: string;
}

/** One screenshot to capture for a story. */
export interface ScreenshotScenario {
  /** Jira story key (e.g. PROJ-123) */
  storyKey: string;
  /** Descriptive label for the screenshot file */
  label: string;
  /** Ordered actions to perform before capturing */
  actions: ScenarioAction[];
  /** If true (default), capture full scrollable page. Set false for viewport only. */
  fullPage?: boolean;
}

/** Input story info for scenario loading. */
export interface StoryInput {
  key: string;
  summary: string;
  description: string;
}

// ---------------------------------------------------------------------------
// Scenario executor
// ---------------------------------------------------------------------------

export async function executeScenario(
  page: Page,
  scenario: ScreenshotScenario,
  port: number,
  screenshotDir: string,
  progress: ProgressReporter,
): Promise<string | null> {
  const { join } = await import("path");

  for (const step of scenario.actions) {
    try {
      switch (step.action) {
        case "navigate": {
          const url = `http://localhost:${port}${step.target}`;
          await page.goto(url, { waitUntil: "networkidle", timeout: 15_000 });
          await page.waitForTimeout(1_000);
          break;
        }
        case "type": {
          const input = await resolveLocator(page, step.target ?? "input");
          await input.first().fill(step.value ?? "", { timeout: 5_000 });
          await page.waitForTimeout(500);
          break;
        }
        case "click": {
          const el = await resolveLocator(page, step.target ?? "button");
          await el.first().click({ timeout: 5_000 });
          await page.waitForTimeout(1_000);
          break;
        }
        case "wait": {
          const timeout = step.value ? parseInt(step.value, 10) : 5_000;
          if (step.target) {
            try {
              const loc = await resolveLocator(page, step.target);
              await loc.first().waitFor({ state: "visible", timeout });
            } catch {
              await page.waitForTimeout(Math.min(timeout, 3_000));
            }
          } else {
            await page.waitForTimeout(timeout);
          }
          break;
        }
        case "clear": {
          const clearInput = await resolveLocator(page, step.target ?? "input");
          await clearInput.first().clear({ timeout: 5_000 });
          await page.waitForTimeout(300);
          break;
        }
        case "press": {
          await page.keyboard.press(step.value ?? "Enter");
          await page.waitForTimeout(500);
          break;
        }
        case "scroll": {
          if (step.target) {
            const el = await resolveLocator(page, step.target);
            await el.first().scrollIntoViewIfNeeded({ timeout: 5_000 });
          } else if (step.value) {
            const pixels = parseInt(step.value, 10);
            await page.evaluate((y) => window.scrollBy(0, y), pixels);
          }
          await page.waitForTimeout(500);
          break;
        }
      }
    } catch (err) {
      progress.warn(
        `    Scenario "${scenario.label}" action ${step.action}(${step.target}) failed: ${(err as Error).message.split("\n")[0]}`
      );
      // Continue — partial state is still worth capturing
    }
  }

  // Capture the screenshot
  const filename = `${scenario.storyKey.toLowerCase()}_${scenario.label}.png`;
  const filepath = join(screenshotDir, filename);
  try {
    await page.screenshot({ path: filepath, fullPage: scenario.fullPage !== false });
    return filepath;
  } catch (err) {
    progress.error(`    Failed to capture "${scenario.label}": ${(err as Error).message.split("\n")[0]}`);
    return null;
  }
}

/**
 * Resolve a target string to a Playwright locator.
 * Tries: placeholder attribute, visible text, then raw CSS selector.
 */
async function resolveLocator(page: Page, target: string) {
  if (/^[.#\[]|[>+~]/.test(target)) {
    return page.locator(target);
  }
  const byPlaceholder = page.getByPlaceholder(target);
  if (await byPlaceholder.count() > 0) return byPlaceholder;
  const byText = page.getByText(target, { exact: false });
  if (await byText.count() > 0) return byText;
  const byRole = page.getByRole("button", { name: target });
  if (await byRole.count() > 0) return byRole;
  return page.locator(target);
}
