/**
 * Release Notes Generator
 *
 * Fetches Jira issues for a given fixVersion, accepts pre-built release notes
 * JSON (generated by Claude in conversation), and optionally publishes to
 * Confluence and Jira version description.
 *
 * Usage:
 *   npx tsx scripts/generate-release-notes.ts v3.40.0 --notes notes.json
 *   npx tsx scripts/generate-release-notes.ts v3.40.0 --notes notes.json --publish
 */

import { JIRA_BASE_URL, credentialProvider } from "./config.js";
import { createJiraClient } from "../src/core/jira-client.js";
import { getCloudId } from "../src/core/cloud-id.js";
import { getVersion, updateVersionDescription } from "../src/core/jira/versions.js";
import { publishToConfluence } from "../src/core/jira/confluence.js";
import { formatPlainText } from "../src/core/ai/release-notes.js";
import { parseJsonResponse } from "../src/core/utils.js";
import type { JiraIssue, ReleaseNotesResult } from "../src/core/types.js";

import { existsSync, readFileSync } from "fs";
import { resolve } from "path";

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

function parseArgs(): { versionName: string; notesFile?: string; publish: boolean; verbose: boolean } {
  const args = process.argv.slice(2);
  const positional: string[] = [];
  let publish = false;
  let verbose = false;
  let notesFile: string | undefined;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--publish") { publish = true; continue; }
    if (args[i] === "--verbose") { verbose = true; continue; }
    if (args[i] === "--notes") { notesFile = args[++i]; continue; }
    if (!args[i].startsWith("--")) positional.push(args[i]);
  }

  if (positional.length === 0) {
    console.error(
      "Usage: npx tsx scripts/generate-release-notes.ts <versionName> --notes <file> [--publish] [--verbose]\n\n" +
        "Example: npx tsx scripts/generate-release-notes.ts v3.40.0 --notes notes.json --publish"
    );
    process.exit(1);
  }

  return { versionName: positional[0], notesFile, publish, verbose };
}

// ---------------------------------------------------------------------------
// Issue Search
// ---------------------------------------------------------------------------

interface SearchResponse {
  issues?: JiraIssue[];
  nextPageToken?: string | null;
  total?: number;
}

async function searchIssues(
  client: Awaited<ReturnType<typeof createJiraClient>>,
  versionName: string,
  verbose: boolean
): Promise<JiraIssue[]> {
  const jql =
    `fixVersion = "${versionName}" AND issuetype not in ` +
    `("Technical Debt", "Security & Compliance", Bug, Spike, Test, Toil, Task)`;

  if (verbose) console.log(`\nJQL: ${jql}\n`);

  const allIssues: JiraIssue[] = [];
  let nextPageToken: string | null = null;

  do {
    const body: Record<string, unknown> = {
      jql,
      fields: [
        "summary",
        "issuetype",
        "project",
        "status",
        "description",
        "customfield_10334",
      ],
      maxResults: 50,
    };
    if (nextPageToken) body.nextPageToken = nextPageToken;

    const res = await client.jiraFetch("/rest/api/3/search/jql", {
      method: "POST",
      body: JSON.stringify(body),
    });
    const data = (await res.json()) as SearchResponse;
    if (data.issues) allIssues.push(...data.issues);
    nextPageToken = data.nextPageToken ?? null;
  } while (nextPageToken);

  return allIssues;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  const { versionName, notesFile, publish, verbose } = parseArgs();
  const client = await createJiraClient(credentialProvider);

  console.log(`\nRelease Notes Generator`);
  console.log(`Version: ${versionName}`);
  console.log(`Mode: ${publish ? "PUBLISH" : "preview"}`);
  console.log("=".repeat(50));

  // 1. Get version metadata
  console.log("\nFetching version metadata...");
  const version = await getVersion(client, versionName, client.credentials.projectKey);
  console.log(
    `  Version ID: ${version.id}, Released: ${version.released ?? "no"}`
  );

  // 2. Get cloud ID
  const cloudId = await getCloudId(JIRA_BASE_URL!);

  // 3. Search issues
  console.log("\nSearching issues...");
  const issues = await searchIssues(client, versionName, verbose);
  console.log(`  Found ${issues.length} issues`);

  if (issues.length === 0) {
    console.log("\nNo issues found for this version. Nothing to generate.");
    return;
  }

  console.log("\nIssues:");
  for (const issue of issues) {
    console.log(
      `  ${issue.key} [${issue.fields.issuetype?.name}] ${issue.fields.summary}`
    );
  }

  // 4. Load pre-built notes
  if (!notesFile) {
    console.log("\n  Issues listed above. Use Claude to generate release notes JSON,");
    console.log("  then re-run with: --notes <file>\n");
    console.log('  The JSON should match: { "summary": "...", "categories": [{ "name": "...", "items": [{ "key": "...", "summary": "..." }] }] }');
    return;
  }

  const notesPath = resolve(notesFile);
  if (!existsSync(notesPath)) {
    console.error(`Notes file not found: ${notesPath}`);
    process.exit(1);
  }
  const notes = parseJsonResponse<ReleaseNotesResult>(readFileSync(notesPath, "utf-8"));

  // 5. Display preview
  const plainText = formatPlainText(notes, versionName);
  console.log("\n" + "=".repeat(60));
  console.log(plainText);
  console.log("=".repeat(60));

  // 6. Publish
  if (publish) {
    console.log("\nPublishing...");

    try {
      const pageUrl = await publishToConfluence(
        client, notes, versionName, cloudId
      );
      console.log(`  Confluence (detailed notes): ${pageUrl}`);
    } catch (err) {
      console.error(
        `  Confluence publish failed: ${(err as Error).message}`
      );
    }

    try {
      await updateVersionDescription(client, version, notes.summary);
      console.log(`  Jira version description (summary): updated`);
    } catch (err) {
      console.error(
        `  Jira version update failed: ${(err as Error).message}`
      );
    }

    console.log("\nDone!");
  } else {
    console.log(
      "\nPreview only. Use --publish to write to Confluence and Jira."
    );
  }
}

main().catch((err) => {
  console.error("\nError:", err.message);
  process.exit(1);
});
